### ISSUE TITLE
Error when lauching sway-alttab

### ISSUE THREAD

**Issue by Simbi0z** [reisub0/sway-alttab#6]
Error: Compat { error: Os { code: 2, kind: NotFound, message: "No such file or directory" } }

Installed from sway-alttab-bin  aur package.

**Comment by Th3Whit3Wolf** [comment]
@zwastik did you add `exec /usr/bin/sway-alttab` or `exec sway-alttab` to your sway config? I installed from AUR and it works for me.

**Comment by kkmp-dk** [comment]
what is the output of this command? 
`$ echo $XDG_RUNTIME_DIR`
and this?
`$ ls -lh /`

**Comment by autolyticus** [comment]
Thanks for the input, as you surmised, I think it most probably would have been due to $XDG_RUNTIME_DIR not being set or being a non-existent directory.

@zwastik In case you are still facing this issue, please feel free to reopen!

**Comment by ghost** [comment]
Hi. 
I can't execute `sway-alttab` in `~/.config/sway/config` file too. But I can execute it from terminal and it works.
> did you add `exec /usr/bin/sway-alttab` or exec `sway-alttab` to your sway config?

I have tried both.

```
$ echo $XDG_RUNTIME_DIR
/run/user/1000

$ ls -lh /
drwxr-xr-x   2 root root 4.0K Feb 22 21:16 bin
drwxr-xr-x   6 root root 2.5K Jan  1  1970 boot
drwxr-xr-x  19 root root 4.5K Mar  3 21:38 dev
drwxr-xr-x  97 root root 4.0K Mar  3 23:03 etc
drwxr-xr-x   3 root root 4.0K Dec  8 16:01 home
drwxr-xr-x  13 root root 4.0K Feb 18 20:16 lib
drwxr-xr-x   7 root root 4.0K Feb 21 23:05 lib64
drwx------   2 root root  16K Dec  8 10:53 lost+found
drwxr-xr-x   2 root root 4.0K Feb 18 20:16 media
drwxr-xr-x   8 root root 4.0K Feb 21 21:32 mnt
drwxr-xr-x   6 root root 4.0K Mar  3 21:57 opt
dr-xr-xr-x 284 root root    0 Mar  3 21:38 proc
drwx------  16 root root 4.0K Mar  3 23:08 root
drwxr-xr-x  20 root root  780 Mar  3 21:47 run
drwxr-xr-x   2 root root  12K Feb 18 20:16 sbin
dr-xr-xr-x  13 root root    0 Mar  3 21:38 sys
drwxrwxrwt  10 root root  64K Mar  3 23:41 tmp
drwxr-xr-x  12 root root 4.0K Feb 22 21:21 usr
drwxr-xr-x   9 root root 4.0K Dec  5 16:42 var
```

I have installed `sway-alttab` by cloning and compiling with `cargo`.
```
$ which sway-alttab
/home/nxjoseph/.cargo/bin/sway-alttab
```

**Comment by ghost** [comment]
I have set `dbus-daemon --session --address=unix:path="$XDG_RUNTIME_DIR/bus"` in `~/.bash_profile` and `sway-alttab` is automatically launched.
```
$ cat ~/.config/sway/config  | grep sway-alt
exec sway-alttab -c "Mod4+Tab"
```
