### ISSUE TITLE
Multiple key binding definitions

### ISSUE THREAD

**Issue by funcrab** [reisub0/sway-alttab#9]
Hello, everyone.

I am using sway-alttab with the following configuration in `~/.config/sway/config`

- `exec sway-alttab -c $mod+tab`

I would like to set it up so that I can use both of the following two key bindings, is there a way to do this?

- $mod+tab
- $mod+semicolon

I set each of the following in `~/.config/sway/config` and restarted sway, but it did not work.

- `exec sway-alttab -c $mod+tab $mod+semicolon`
- `bindsym $mod+semicolon $mod+tab`

**Comment by kerneis-anssi** [comment]
The daemon can only install a single binding for you (-c takes a single value). You must send a SIGUSR1 signal to the daemon, so something along the lines of the following (not tested, not sure if variable expansion will work as expected):

bindsym $mod+semicolon exec pkill -USR1 -F ${XDG_RUNTIME_DIR:-/tmp}/sway-alttab.pid

**Comment by funcrab** [comment]
Thanks. I am currently using `swayr` to achieve the relevant functionality as an alternative to this.
https://sr.ht/~tsdh/swayr/
```
bindsym $mod+tab       exec swayr switch-to-urgent-or-lru-window
bindsym $mod+semicolon exec swayr switch-to-urgent-or-lru-window
```

**Comment by autolyticus** [comment]
Thanks for mentioning that! `swayr` looks great! And it also seems to be actively maintained (unlike this repo which does its job but is hard for me to improve as I do not use Sway anymore). I think I will mention it as an alternative in the README
